spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
    
logging:
  level:
    root: info
    
    
kiwayMarketplace:
  uploadFilePath : ${web.web-path}
   
server:
  port: 8086
  context-path: /
mybatis-plus:
  mapper-locations: classpath:/**/mapper/*Mapper.xml
  typeAliasesPackage: cn.kiway.**.entity
  global-config:
    id-type: 3
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    isRefresh: true
    capital-mode: true
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    jdbc-type-for-null: 'null'