web:
  web-path: /usr/local/project/ai/
spring:
  datasource:
    url: jdbc:mysql://192.168.105.196:3306/kiway_ai?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - classpath:/file/
    - file:${web.web-path}
    
    
logging:
  level:
    root: info
    
    
kiwayMarketplace:
  baseUrl: http://ai.kiway.cn